# Generated by Django 5.2.17 on 2026-08-24 16:46

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgaBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejecutada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('ejecutada_por', models.CharField(max_length=150)),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('eventos_archivados', models.BigIntegerField(default=0)),
                ('archivo', models.CharField(blank=True, max_length=500)),
                ('hash_archivo', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Purga de bitácora',
                'verbose_name_plural': 'Purgas de bitácora',
                'ordering': ('-ejecutada_en',),
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('username', models.CharField(blank=True, db_index=True, help_text='Se conserva aunque el usuario se elimine: la evidencia no puede depender de una FK que puede quedar nula.', max_length=150, verbose_name='Usuario (texto)')),
                ('perfil', models.CharField(blank=True, max_length=64, verbose_name='Perfil vigente')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAIL', 'Intento de acceso fallido'), ('LOGOUT', 'Cierre de sesión'), ('CONSULTA', 'Consulta / lectura'), ('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ELIMINACION', 'Eliminación'), ('RESTAURACION', 'Restauración'), ('EXPORTACION', 'Exportación de datos'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CAMBIO_PERMISO', 'Cambio de permisos o perfil'), ('CAMBIO_PWD', 'Cambio de contraseña'), ('DENEGADO', 'Acceso denegado'), ('ADMIN', 'Operación administrativa')], db_index=True, max_length=16, verbose_name='Acción')),
                ('modelo', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Entidad')),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Id del objeto')),
                ('objeto_repr', models.CharField(blank=True, max_length=300, verbose_name='Descripción del objeto')),
                ('exitoso', models.BooleanField(db_index=True, default=True, verbose_name='Exitoso')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='Agente de usuario')),
                ('ruta', models.CharField(blank=True, max_length=300, verbose_name='Ruta')),
                ('metodo', models.CharField(blank=True, max_length=8, verbose_name='Método HTTP')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('detalle', apps.core.fields.EncryptedTextField(aad_scope='auditoria.detalle', blank=True, help_text='JSON con los valores anteriores y nuevos. Cifrado porque puede contener datos personales.', verbose_name='Detalle (cifrado)')),
                ('hash_anterior', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', editable=False, max_length=64)),
                ('hash_actual', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Bitácora de auditoría',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['-fecha', 'accion'], name='aud_fecha_accion_idx'), models.Index(fields=['modelo', 'objeto_id', '-fecha'], name='aud_objeto_idx'), models.Index(fields=['username', '-fecha'], name='aud_usuario_idx')],
            },
        ),
    ]
