# Generated by Django 5.2.17 on 2026-08-24 16:46

import apps.accounts.models
import apps.core.fields
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', apps.core.fields.EncryptedCharField(aad_scope='usuario.first_name', blank=True, max_length=512, verbose_name='Nombres')),
                ('last_name', apps.core.fields.EncryptedCharField(aad_scope='usuario.last_name', blank=True, max_length=512, verbose_name='Apellidos')),
                ('email', apps.core.fields.EncryptedEmailField(aad_scope='usuario.email', blank=True, max_length=512, verbose_name='Correo electrónico')),
                ('email_bidx', apps.core.fields.BlindIndexField(blank=True, db_index=True, editable=False, max_length=32, scope='usuario.email', source='email')),
                ('documento', apps.core.fields.EncryptedCharField(aad_scope='usuario.documento', blank=True, max_length=512, verbose_name='Documento de identidad')),
                ('documento_bidx', apps.core.fields.BlindIndexField(blank=True, db_index=True, editable=False, max_length=32, scope='usuario.documento', source='documento')),
                ('telefono', apps.core.fields.EncryptedCharField(aad_scope='usuario.telefono', blank=True, max_length=512, verbose_name='Teléfono')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('mfa_habilitado', models.BooleanField(default=False, verbose_name='MFA habilitado')),
                ('debe_cambiar_password', models.BooleanField(default=True, verbose_name='Debe cambiar la contraseña')),
                ('ultimo_cambio_password', models.DateTimeField(blank=True, null=True, verbose_name='Último cambio de contraseña')),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ('username',),
                'permissions': [('gestionar_accesos', 'Puede gestionar perfiles, permisos y accesos'), ('ver_bitacora', 'Puede consultar la bitácora de auditoría'), ('exportar_datos', 'Puede exportar información del sistema')],
            },
            managers=[
                ('objects', apps.accounts.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=64, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_sistema', models.BooleanField(default=False, help_text='Los perfiles de sistema no pueden eliminarse ni renombrarse.', verbose_name='Perfil de sistema')),
                ('permite_edicion_permisos', models.BooleanField(default=True, help_text='ADMINISTRADOR y AUDITOR tienen permisos fijos por diseño.', verbose_name='Permite editar sus permisos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='SesionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('inicio', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('exitosa', models.BooleanField(default=True)),
                ('motivo_fallo', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Sesión de acceso',
                'verbose_name_plural': 'Sesiones de acceso',
                'ordering': ('-inicio',),
            },
        ),
    ]
