# Generated by Django 5.0.9 on 2026-08-27 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('codigo', models.CharField(help_text='Ej.: RAT-SUS-01', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9\\-\\.]{2,29}$', 'Use mayúsculas, números, guiones y puntos. Ej.: RAT-SUS-01')], verbose_name='3.1 Código único')),
                ('nombre_corto', models.CharField(help_text='Ej.: Evaluación de riesgo y capacidad de pago para suscripción de fianzas.', max_length=180, verbose_name='3.1 Nombre corto de la actividad')),
                ('finalidad', models.TextField(help_text="Para qué se tratan los datos. Una fila por finalidad. 'Base de clientes' no es una finalidad, es un soporte.", verbose_name='3.1 Finalidad (una frase)')),
                ('responsable_cargo', models.CharField(help_text='Cargo, no nombre propio. El responsable del tratamiento ante la ley es la compañía.', max_length=180, verbose_name='3.3 Responsable del área (cargo)')),
                ('corresponsable_situacion', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No / No aplica'), ('PEND', 'Pendiente de evaluar')], default='NO', help_text='Solo si otra entidad decide CONJUNTAMENTE fines y medios (Art. 37 RLOPDP). Un corredor de seguros normalmente NO es corresponsable.', max_length=4, verbose_name='3.4 ¿Existe corresponsable?')),
                ('corresponsable_detalle', models.TextField(blank=True, help_text='Contrato que reparte tareas; la responsabilidad es solidaria.', verbose_name='3.4 Detalle del reparto de tareas')),
                ('aplica_art28', models.BooleanField(default=False, help_text='Licitud presunta para fines de solvencia patrimonial cuando los datos vienen de fuentes públicas o del acreedor. Restringido a esa única finalidad.', verbose_name='3.6 Datos crediticios — Art. 28 LOPDP')),
                ('datos_especiales', models.BooleanField(default=False, help_text='Sensibles, de niñas/niños/adolescentes, de salud o de discapacidad. El pasado judicial pedido en debida diligencia cuenta.', verbose_name='3.9 ¿Datos especiales? (Art. 25 LOPDP)')),
                ('habilitante_justificacion', models.TextField(blank=True, verbose_name='3.7 Justificación del habilitante')),
                ('menores', models.BooleanField(default=False, help_text='Cargas familiares, beneficiarios de desgravamen, hijos en encuestas o eventos.', verbose_name='3.11 ¿Datos de menores?')),
                ('menores_consentimiento_representante', models.BooleanField(default=False, help_text='Art. 19 RLOPDP: menores de 15 años. Desde los 15, el adolescente puede consentir.', verbose_name='Consentimiento del representante legal verificado')),
                ('menores_interes_superior', models.BooleanField(default=False, verbose_name='Interés superior del niño evaluado (Art. 20 RLOPDP)')),
                ('menores_informacion_representante', models.BooleanField(default=False, verbose_name='Información dirigida al representante (Art. 12 LOPDP)')),
                ('menores_sin_decisiones_automatizadas', models.BooleanField(default=False, verbose_name='Sin decisiones automatizadas sobre menores (Art. 21 LOPDP)')),
                ('destinatarios_internos', models.TextField(help_text='Criterio de necesidad de conocer. Insumo de la matriz de control de accesos. Ej.: Suscripción, Comité de Riesgos, Cobranzas, Auditoría Interna.', verbose_name='3.12 Destinatarios internos (áreas / cargos con acceso)')),
                ('transferencia_internacional', models.BooleanField(default=False, help_text='Sí también cuando los datos son ACCESIBLES desde el exterior: nube con servidores fuera del país, casa matriz, soporte remoto, reaseguro internacional.', verbose_name='3.14 ¿Transferencia internacional?')),
                ('plazo_conservacion', models.CharField(help_text='Plazo concreto. Ej.: vigencia de la póliza + 10 años de prescripción.', max_length=255, verbose_name='3.16 Plazo de conservación')),
                ('criterio_plazo', models.TextField(help_text='Norma legal expresa (cítela), plazo de prescripción, duración del contrato + defensa de reclamaciones (Art. 11 núm. 2 RLOPDP) o decisión interna motivada.', verbose_name='3.17 Criterio de determinación del plazo')),
                ('destino_final', models.CharField(choices=[('ELIM', 'Eliminación segura'), ('BLOQ', 'Bloqueo'), ('ANON', 'Anonimización')], default='ELIM', help_text='Art. 9 RLOPDP.', max_length=4, verbose_name='3.17 Destino final de los datos')),
                ('medidas_adicionales', models.TextField(blank=True, help_text='Describa por referencia a controles. No incluya detalle confidencial (claves, rutas, configuraciones).', verbose_name='3.18 Medidas adicionales')),
                ('eipd_requerida', models.BooleanField(default=False, help_text='Obligatoria y PREVIA al tratamiento (Art. 42 LOPDP, Arts. 29-32 RLOPDP).', verbose_name='3.19 ¿EIPD requerida?')),
                ('eipd_codigo', models.CharField(blank=True, max_length=60, verbose_name='3.19 Código de la EIPD')),
                ('eipd_fecha', models.DateField(blank=True, null=True, verbose_name='3.19 Fecha de la EIPD')),
                ('consulta_spdp', models.BooleanField(default=False, help_text='En caso de duda, la Autoridad responde en término de 5 días (Art. 31 RLOPDP).', verbose_name='Consulta previa a la SPDP')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='3.20 Versión')),
                ('fecha_cese', models.DateField(blank=True, help_text='Obligatoria en estado Histórico/Cesado, para conservar la trazabilidad.', null=True, verbose_name='3.20 Fecha de cese')),
                ('fecha_validacion', models.DateField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('validado_por_cargo', models.CharField(blank=True, help_text='Dueño del proceso y DPD.', max_length=180, verbose_name='Validado por (cargo)')),
                ('reportado_registro_nacional', models.BooleanField(default=False, verbose_name='Reportado al Registro Nacional')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('area', models.ForeignKey(help_text='Si intervienen varias, registre la que decide la finalidad; las demás van en destinatarios internos (3.12).', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='catalogos.area', verbose_name='3.2 Área dueña del proceso')),
                ('categorias_datos', models.ManyToManyField(related_name='actividades', to='catalogos.categoriadato', verbose_name='3.8 Categorías de datos personales')),
                ('categorias_interesados', models.ManyToManyField(related_name='actividades', to='catalogos.categoriainteresado', verbose_name='3.10 Categorías de interesados (titulares)')),
                ('corresponsables', models.ManyToManyField(blank=True, limit_choices_to={'activo': True, 'rol': 'COR'}, related_name='actividades_corresponsable', to='catalogos.tercero', verbose_name='3.4 Corresponsables')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('criterios_eipd', models.ManyToManyField(blank=True, related_name='actividades', to='catalogos.criterioeipd', verbose_name='3.19 Criterios que activan la EIPD')),
                ('encargados', models.ManyToManyField(blank=True, help_text='Tratan datos POR CUENTA de la compañía y bajo sus instrucciones (Art. 34 LOPDP). Si el tercero decide para qué usa los datos, es destinatario (3.13), no encargado.', limit_choices_to={'activo': True, 'rol': 'ENC'}, related_name='actividades_encargado', to='catalogos.tercero', verbose_name='3.5 Encargados del tratamiento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='catalogos.estadoregistro', verbose_name='3.20 Estado del registro')),
                ('habilitantes_especiales', models.ManyToManyField(blank=True, related_name='actividades', to='catalogos.habilitanteespecial', verbose_name='3.7 Habilitante para categorías especiales (Art. 26)')),
                ('medidas_seguridad', models.ManyToManyField(blank=True, related_name='actividades', to='catalogos.medidaseguridad', verbose_name='3.18 Medidas técnicas y organizativas')),
                ('proceso_interno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='catalogos.procesointerno', verbose_name='3.12 Proceso interno')),
            ],
            options={
                'verbose_name': 'Actividad de tratamiento',
                'verbose_name_plural': 'Actividades de tratamiento',
                'ordering': ('codigo',),
                'permissions': [('validar_actividad', 'Puede validar y cambiar el estado de una actividad'), ('exportar_rat', 'Puede exportar el RAT completo')],
            },
        ),
        migrations.CreateModel(
            name='BaseLicitudActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.CharField(help_text='Por qué esta base cubre esta finalidad concreta.', max_length=500, verbose_name='Justificación (una línea)')),
                ('test_ponderacion', models.TextField(blank=True, help_text='Obligatorio para interés legítimo (Art. 7 núm. 3 RLOPDP): interés perseguido, necesidad, y por qué no prevalecen los derechos del titular.', verbose_name='Test de ponderación')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rat.actividadtratamiento')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.baselicitud')),
            ],
            options={
                'verbose_name': 'Base de licitud aplicada',
                'verbose_name_plural': 'Bases de licitud aplicadas',
                'ordering': ('base__orden',),
                'unique_together': {('actividad', 'base')},
            },
        ),
        migrations.AddField(
            model_name='actividadtratamiento',
            name='bases_licitud',
            field=models.ManyToManyField(related_name='actividades', through='rat.BaseLicitudActividad', to='catalogos.baselicitud', verbose_name='3.6 Bases de licitud (Art. 7 LOPDP)'),
        ),
        migrations.CreateModel(
            name='DestinatarioExternoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundamento', models.CharField(help_text='Causal de legitimidad + consentimiento, o excepción del Art. 36 (obligación legal, requerimiento de autoridad, fuentes públicas, relación jurídica, urgencia vital, estudios epidemiológicos).', max_length=500, verbose_name='Fundamento de la comunicación')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rat.actividadtratamiento')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.destinatarioexterno')),
            ],
            options={
                'verbose_name': 'Destinatario externo de la actividad',
                'verbose_name_plural': 'Destinatarios externos de la actividad',
                'ordering': ('destinatario__orden',),
                'unique_together': {('actividad', 'destinatario')},
            },
        ),
        migrations.AddField(
            model_name='actividadtratamiento',
            name='destinatarios_externos',
            field=models.ManyToManyField(related_name='actividades', through='rat.DestinatarioExternoActividad', to='catalogos.destinatarioexterno', verbose_name='3.13 Destinatarios externos'),
        ),
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Versión')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('nota', models.CharField(blank=True, max_length=500, verbose_name='Nota del cambio')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='rat.actividadtratamiento')),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.estadoregistro', verbose_name='Estado anterior')),
                ('estado_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogos.estadoregistro', verbose_name='Estado nuevo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de historial',
                'verbose_name_plural': 'Historial',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, help_text='Ej.: cláusulas tipo avaladas por la Autoridad, contrato de reaseguro, región de alojamiento del proveedor cloud.', max_length=500, verbose_name='Detalle / instrumento')),
                ('destinatario_exterior', models.CharField(blank=True, max_length=255, verbose_name='Destinatario en el exterior')),
                ('registrada_registro_nacional', models.BooleanField(default=False, help_text='Art. 59 LOPDP / Art. 78 RLOPDP: país, categorías, finalidad, destinatario, mecanismo.', verbose_name='Registrada en el Registro Nacional')),
                ('fecha_registro', models.DateField(blank=True, null=True, verbose_name='Fecha de registro')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='rat.actividadtratamiento')),
                ('mecanismo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.mecanismotransferencia', verbose_name='Mecanismo habilitante')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.pais', verbose_name='País destino')),
            ],
            options={
                'verbose_name': 'Transferencia internacional',
                'verbose_name_plural': 'Transferencias internacionales',
                'ordering': ('pais__nombre',),
            },
        ),
    ]
