# Generated by Django 5.0.9 on 2026-08-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadtratamiento',
            name='corresponsables',
        ),
        migrations.AddField(
            model_name='actividadtratamiento',
            name='corresponsables',
            field=models.CharField(blank=True, help_text='Razón social de cada entidad que decide conjuntamente fines y medios. Separe con punto y coma si hay varias.', max_length=500, verbose_name='3.4 Corresponsables'),
        ),
    ]
