# Generated by Django 5.0.9 on 2026-08-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat', '0002_remove_actividadtratamiento_corresponsables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadtratamiento',
            name='encargados_contrato_art41',
            field=models.BooleanField(default=False, help_text='Todos los encargados listados tienen contrato con las cláusulas del Art. 41 RLOPDP y acuerdo de confidencialidad (Art. 47 núm. 10 LOPDP).', verbose_name='Contratos de encargo verificados'),
        ),
        migrations.RemoveField(
            model_name='actividadtratamiento',
            name='encargados',
        ),
        migrations.AddField(
            model_name='actividadtratamiento',
            name='encargados',
            field=models.TextField(blank=True, help_text='Razón social de cada encargado; separe con punto y coma. Tratan datos POR CUENTA de la compañía y bajo sus instrucciones (Art. 34 LOPDP). Si el tercero decide para qué usa los datos, es destinatario (3.13), no encargado.', verbose_name='3.5 Encargados del tratamiento'),
        ),
    ]
