// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf0QlUWqVm_aGStHdKroTSGfH0pGmOV7A',
    appId: '1:95672289191:web:4e73a1af1ba5ea5fbdd882',
    messagingSenderId: '95672289191',
    projectId: 'tienda-eela',
    authDomain: 'tienda-eela.firebaseapp.com',
    storageBucket: 'tienda-eela.firebasestorage.app',
    measurementId: 'G-BTYVFGVYJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQyusb_0SFEmK8HRHX9UZOIIkj54su4xc',
    appId: '1:95672289191:android:e07cb4603f681364bdd882',
    messagingSenderId: '95672289191',
    projectId: 'tienda-eela',
    storageBucket: 'tienda-eela.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLvEn7ttWtzuDMaherstKap3TpBWzH7GI',
    appId: '1:95672289191:ios:42e726419ec8fb89bdd882',
    messagingSenderId: '95672289191',
    projectId: 'tienda-eela',
    storageBucket: 'tienda-eela.firebasestorage.app',
    iosBundleId: 'com.example.tienda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLvEn7ttWtzuDMaherstKap3TpBWzH7GI',
    appId: '1:95672289191:ios:42e726419ec8fb89bdd882',
    messagingSenderId: '95672289191',
    projectId: 'tienda-eela',
    storageBucket: 'tienda-eela.firebasestorage.app',
    iosBundleId: 'com.example.tienda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf0QlUWqVm_aGStHdKroTSGfH0pGmOV7A',
    appId: '1:95672289191:web:e3e2c60e0856d1e1bdd882',
    messagingSenderId: '95672289191',
    projectId: 'tienda-eela',
    authDomain: 'tienda-eela.firebaseapp.com',
    storageBucket: 'tienda-eela.firebasestorage.app',
    measurementId: 'G-JZHRMKGWLL',
  );
}
