# Generated by Django 6.1 on 2026-08-30 00:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de gasto',
                'verbose_name_plural': 'Tipos de gasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('costo_previsto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_real', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL)),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.tipogasto')),
            ],
            options={
                'ordering': ['-fecha', '-codigo'],
            },
        ),
    ]
