# Generated by Django 5.2.17 on 2026-08-24 16:46

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('plantillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(db_index=True, help_text='Formato sugerido RAT-<ÁREA>-<NN>. Ej.: RAT-SUS-01.', max_length=32, unique=True, verbose_name='3.1 Código')),
                ('nombre', models.CharField(db_index=True, help_text='Acción + finalidad. Correcto: «Evaluación de riesgo y capacidad de pago para suscripción». Incorrecto: «Base de clientes» (eso es un soporte).', max_length=300, verbose_name='3.1 Actividad / Proceso de tratamiento')),
                ('finalidad', models.TextField(help_text='Una sola finalidad por fila, con verbos concretos: evaluar, emitir, cobrar, reportar. Si necesita tres bases legales distintas, probablemente son tres actividades.', verbose_name='Finalidad concreta')),
                ('cargo_responsable', models.CharField(help_text='Cargo, no nombre propio, para que la matriz no caduque con la rotación.', max_length=200, verbose_name='3.3 Responsable del área (cargo)')),
                ('justificacion_base_licitud', models.TextField(help_text='Una línea por numeral invocado. Para datos crediticios añada la referencia al Art. 28 LOPDP.', verbose_name='Justificación de la base de licitud')),
                ('test_ponderacion_codigo', models.CharField(blank=True, help_text='Obligatorio si invoca interés legítimo (Art. 7 núm. 3 RLOPDP). Ej.: TP-2026-01.', max_length=64, verbose_name='Código del test de ponderación')),
                ('datos_especiales', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No aplica'), ('NE', 'No evaluado')], db_index=True, default='NE', max_length=2, verbose_name='3.9 ¿Datos especiales?')),
                ('tipos_dato_especial', models.JSONField(blank=True, default=list, help_text='Trazabilidad fina: SENSIBLE, SALUD, BIOMETRICO, JUDICIAL, CREDITICIO, MENORES, DISCAPACIDAD.', verbose_name='Tipos de dato especial')),
                ('menores', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No aplica'), ('NE', 'No evaluado')], db_index=True, default='NE', max_length=2, verbose_name='3.11 ¿Datos de menores?')),
                ('menores_detalle', models.CharField(blank=True, help_text='Si SÍ: verificar consentimiento del representante legal (Art. 19 RLOPDP) y prohibición reforzada de decisiones automatizadas (Art. 21 LOPDP).', max_length=300, verbose_name='Detalle de menores')),
                ('fundamento_comunicacion', models.TextField(blank=True, help_text='Art. 33 LOPDP (causal + consentimiento) o excepciones del Art. 36.', verbose_name='Fundamento de la comunicación a terceros')),
                ('transferencia_internacional', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No aplica'), ('NE', 'No evaluado')], db_index=True, default='NE', help_text='SÍ si los datos salen del Ecuador O son accesibles desde el exterior. La nube extranjera cuenta aunque «solo almacene».', max_length=2, verbose_name='3.14 ¿Transferencia internacional?')),
                ('garantias_detalle', models.TextField(blank=True, help_text='Ej.: «Alemania — contrato de reaseguro con anexo DP-2025». No cite solo «SCC/BCR»: son figuras del RGPD.', verbose_name='Detalle de garantías')),
                ('reportada_registro_nacional', models.BooleanField(default=False, help_text='Art. 51 LOPDP y Art. 86 RLOPDP: término de 10 días desde el inicio del tratamiento.', verbose_name='Reportada al Registro Nacional')),
                ('fecha_reporte_registro_nacional', models.DateField(blank=True, null=True)),
                ('plazo_conservacion', models.CharField(help_text='Plazo concreto desde un hito verificable. Evite «indefinido».', max_length=300, verbose_name='3.16 Plazo de conservación')),
                ('plazo_meses', models.PositiveIntegerField(blank=True, help_text='Permite calcular indicadores y alertas de depuración.', null=True, verbose_name='Plazo en meses (normalizado)')),
                ('criterio_detalle', models.TextField(blank=True, verbose_name='Detalle del criterio')),
                ('destino_final', models.CharField(blank=True, choices=[('ELIMINACION', 'Eliminación segura'), ('BLOQUEO', 'Bloqueo'), ('ANONIMIZACION', 'Anonimización')], help_text='Art. 9 RLOPDP.', max_length=16, verbose_name='Destino final del dato')),
                ('medidas_detalle', apps.core.fields.EncryptedTextField(aad_scope='rat.medidas_detalle', blank=True, help_text='Cifrado: el detalle de controles es información de seguridad cuya divulgación facilitaría un ataque. El procedimiento §3.18 pide describir «por referencia a controles, no en detalle confidencial».', verbose_name='Detalle de medidas (confidencial)')),
                ('eipd_requerida', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No aplica'), ('NE', 'No evaluado')], db_index=True, default='NE', max_length=2, verbose_name='3.19 ¿EIPD requerida?')),
                ('eipd_codigo', models.CharField(blank=True, max_length=64, verbose_name='Código de la EIPD')),
                ('eipd_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de la EIPD')),
                ('decision_automatizada', models.BooleanField(db_index=True, default=False, help_text='Si es SÍ con efectos jurídicos, la EIPD es obligatoria y PREVIA (Art. 42 lit. a LOPDP) e informa el derecho del Art. 20.', verbose_name='¿Decisión automatizada / scoring?')),
                ('intervencion_humana', models.BooleanField(default=True, verbose_name='Existe intervención humana en la decisión')),
                ('gran_escala', models.BooleanField(default=False, help_text='Criterios del Art. 4 núm. 7 RLOPDP y MTGE de la SPDP.', verbose_name='¿Tratamiento a gran escala?')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_VALIDACION', 'En validación'), ('VALIDADO', 'Validado'), ('VIGENTE', 'Vigente / Publicado'), ('CON_BRECHAS', 'Con brechas'), ('EN_REVISION', 'En revisión'), ('HISTORICO', 'Histórico / Cesado')], db_index=True, default='BORRADOR', max_length=16, verbose_name='3.20 Estado del registro')),
                ('version', models.CharField(default='1.0', max_length=16, verbose_name='Versión')),
                ('fecha_inicio_tratamiento', models.DateField(blank=True, null=True, verbose_name='Inicio del tratamiento')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='Fecha de cese')),
                ('fecha_ultima_revision', models.DateField(blank=True, db_index=True, null=True, verbose_name='Última revisión')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', apps.core.fields.EncryptedTextField(aad_scope='rat.observaciones', blank=True, help_text='Campo libre: puede contener nombres de personas mencionadas en entrevistas, por lo que se cifra por precaución.', verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('area', models.ForeignKey(help_text='Área que decide la finalidad. Las demás van en 3.12.', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='catalogos.area', verbose_name='3.2 Área / Unidad organizativa')),
                ('bases_licitud', models.ManyToManyField(related_name='actividades', to='catalogos.baselicitud', verbose_name='3.6 Base de licitud (Art. 7 LOPDP)')),
                ('categorias_datos', models.ManyToManyField(related_name='actividades', to='catalogos.categoriadato', verbose_name='3.8 Categorías de datos personales')),
                ('categorias_titulares', models.ManyToManyField(related_name='actividades', to='catalogos.categoriatitular', verbose_name='3.10 Categorías de interesados')),
                ('corresponsables', models.ManyToManyField(blank=True, help_text='Solo si otra entidad decide CONJUNTAMENTE fines y medios (Art. 37 RLOPDP). Un corredor normalmente NO es corresponsable.', related_name='actividades_corresponsable', to='catalogos.tercero', verbose_name='3.4 Corresponsables')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('criterio_conservacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='catalogos.criterioconservacion', verbose_name='3.17 Criterio de determinación')),
                ('destinatarios_externos', models.ManyToManyField(blank=True, related_name='actividades_destinatario', to='catalogos.tercero', verbose_name='3.13 Destinatarios externos')),
                ('destinatarios_internos', models.ManyToManyField(blank=True, help_text='Insumo directo de la matriz de control de accesos.', related_name='actividades_receptoras', to='catalogos.area', verbose_name='3.12 Destinatarios internos')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('encargados', models.ManyToManyField(blank=True, help_text='Terceros que tratan datos POR CUENTA de la compañía (Art. 34 LOPDP). Si el tercero decide para qué usa los datos, va en 3.13.', related_name='actividades_encargado', to='catalogos.tercero', verbose_name='3.5 Encargados de tratamiento')),
                ('habilitantes_especiales', models.ManyToManyField(blank=True, related_name='actividades', to='catalogos.habilitanteespecial', verbose_name='3.7 Habilitante (Art. 26 LOPDP)')),
                ('mecanismos_transferencia', models.ManyToManyField(blank=True, related_name='actividades', to='catalogos.mecanismotransferencia', verbose_name='3.15 Mecanismos habilitantes')),
                ('medidas_seguridad', models.ManyToManyField(blank=True, related_name='actividades', to='catalogos.medidaseguridad', verbose_name='3.18 Medidas de seguridad')),
                ('paises_destino', models.ManyToManyField(blank=True, related_name='actividades', to='catalogos.pais', verbose_name='3.15 Países destino')),
                ('sistemas', models.ManyToManyField(blank=True, related_name='actividades', to='catalogos.sistemainformacion', verbose_name='Sistemas/soportes')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Actividad de tratamiento',
                'verbose_name_plural': 'Actividades de tratamiento (RAT)',
                'ordering': ('codigo',),
                'permissions': [('validar_actividad', 'Puede validar actividades de tratamiento'), ('publicar_actividad', 'Puede publicar (poner vigente) actividades'), ('exportar_rat', 'Puede exportar la matriz RAT')],
            },
        ),
        migrations.CreateModel(
            name='Brecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Falta contrato de encargado'), ('BASE_LEGAL', 'Base de licitud débil o ausente'), ('PLAZO', 'Plazo de conservación indefinido'), ('EIPD', 'EIPD pendiente'), ('TRANSFERENCIA', 'Transferencia sin mecanismo habilitante'), ('CONSENTIMIENTO', 'Consentimiento no evidenciado'), ('SEGURIDAD', 'Medida de seguridad faltante'), ('OTRO', 'Otro')], db_index=True, max_length=16)),
                ('descripcion', models.TextField()),
                ('accion', models.TextField(verbose_name='Acción correctiva')),
                ('fecha_compromiso', models.DateField(blank=True, db_index=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada'), ('ACEPTADA', 'Riesgo aceptado')], db_index=True, default='ABIERTA', max_length=12)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brechas', to='rat.actividadtratamiento')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brechas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brecha',
                'verbose_name_plural': 'Brechas y planes de acción',
                'ordering': ('fecha_compromiso', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('entrevistados', apps.core.fields.EncryptedTextField(aad_scope='rat.entrevistados', blank=True, verbose_name='Entrevistados (cargo y nombre)')),
                ('respuestas', apps.core.fields.EncryptedTextField(aad_scope='rat.entrevista_respuestas', blank=True, verbose_name='Respuestas al cuestionario')),
                ('confirmada_por_area', models.BooleanField(default=False, help_text='Regla de cierre: repetir la lista de actividades identificadas y pedir confirmación expresa.', verbose_name='Confirmada por el área')),
                ('actividades', models.ManyToManyField(blank=True, related_name='entrevistas', to='rat.actividadtratamiento')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas', to='catalogos.area')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas', to='plantillas.plantilla')),
            ],
            options={
                'verbose_name': 'Entrevista de levantamiento',
                'verbose_name_plural': 'Entrevistas de levantamiento',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_VALIDACION', 'En validación'), ('VALIDADO', 'Validado'), ('VIGENTE', 'Vigente / Publicado'), ('CON_BRECHAS', 'Con brechas'), ('EN_REVISION', 'En revisión'), ('HISTORICO', 'Histórico / Cesado')], max_length=16)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_VALIDACION', 'En validación'), ('VALIDADO', 'Validado'), ('VIGENTE', 'Vigente / Publicado'), ('CON_BRECHAS', 'Con brechas'), ('EN_REVISION', 'En revisión'), ('HISTORICO', 'Histórico / Cesado')], max_length=16)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='rat.actividadtratamiento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ('-fecha',),
            },
        ),
        migrations.AddIndex(
            model_name='actividadtratamiento',
            index=models.Index(fields=['estado', 'area'], name='rat_activid_estado_154fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='actividadtratamiento',
            index=models.Index(fields=['datos_especiales', 'estado'], name='rat_activid_datos_e_287fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='actividadtratamiento',
            index=models.Index(fields=['transferencia_internacional'], name='rat_activid_transfe_e7e851_idx'),
        ),
        migrations.AddIndex(
            model_name='actividadtratamiento',
            index=models.Index(fields=['-actualizado_en'], name='rat_activid_actuali_58ee9d_idx'),
        ),
    ]
