# Generated by Django 5.2.17 on 2026-08-24 16:46

import apps.core.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=64, unique=True, verbose_name='Código del documento')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('datos', models.JSONField(blank=True, default=dict, verbose_name='Datos del formulario')),
                ('contenido', apps.core.fields.EncryptedTextField(aad_scope='plantillas.documento', blank=True, verbose_name='Contenido renderizado')),
                ('aprobado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Documento generado',
                'verbose_name_plural': 'Documentos generados',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('eliminado_en', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Eliminado en')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.SlugField(max_length=64, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('CUESTIONARIO', 'Cuestionario de levantamiento'), ('EIPD', 'Evaluación de impacto (EIPD)'), ('TEST_POND', 'Test de ponderación de interés legítimo'), ('AVISO', 'Aviso / política de privacidad'), ('CONTRATO', 'Contrato de encargo (Art. 41 RLOPDP)'), ('VULNERACION', 'Notificación de vulneración (Arts. 43–46)'), ('ACTA', 'Acta de entrevista'), ('INFORME', 'Informe / reporte'), ('CORREO', 'Correo o notificación'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=16, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cuerpo', models.TextField(help_text='Variables disponibles: {{ actividad }}, {{ area }}, {{ usuario }}, {{ fecha }}, {{ organizacion }} y las claves de esquema_campos.', verbose_name='Cuerpo (Django Template Language)')),
                ('esquema_campos', models.JSONField(blank=True, default=list, help_text='Lista de objetos: [{"nombre":"riesgo","etiqueta":"Riesgo identificado","tipo":"texto","requerido":true}]. Tipos: texto, area, numero, fecha, booleano, seleccion.', verbose_name='Esquema de campos')),
                ('version', models.CharField(default='1.0', max_length=16, verbose_name='Versión')),
                ('activa', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('es_sistema', models.BooleanField(default=False, help_text='Las plantillas base no se eliminan; se clonan para adaptarlas.', verbose_name='Plantilla base del sistema')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ('tipo', 'codigo'),
            },
        ),
    ]
